# SELECT COUNT(*)
# FROM USER_INFO joined2021
# WHERE JOINED LIKE '2021%'

# SELECT COUNT(*)
# FROM USER_INFO U
# JOIN ONLINE_SALE S
# ON U.USER_ID = S.USER_ID
# WHERE U.USER_ID = ANY(
#     SELECT U.USER_ID 
#     FROM USER_INFO 
#     WHERE JOINED 
#     LIKE '2021%')

SELECT 
    YEAR,
    MONTH,
    COUNT(*) AS PUCHASED_USERS,
    ROUND( 
        COUNT(*) / 
            (SELECT COUNT(*)
            FROM USER_INFO 
            WHERE JOINED LIKE '2021%') , 1) AS PUCHASED_RATIO
FROM (
    SELECT DISTINCT
        YEAR(S.SALES_DATE) AS YEAR, 
        MONTH(S.SALES_DATE) AS MONTH, 
        U.USER_ID
    FROM USER_INFO U
    JOIN ONLINE_SALE S
    ON U.USER_ID = S.USER_ID AND YEAR(U.JOINED)=2021
) PUCHASED_IN_2021

GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH


# USER_INFO U
# JOIN ONLINE_SALE S
# ON U.USER_ID = S.USER_ID
# WHERE U.USER_ID = ANY(
#     SELECT DISTINCT U.USER_ID 
#     FROM USER_INFO 
#     WHERE JOINED 
#     LIKE '2021%')